language: node_js
deploy:
  api_key:
    secure: DwyZ8/VTvZuHbSIt6ugGpfs3xZ1QD8qIt5iO6RudXru/xEMJLAPjL5U/9bMUS1b5tWpfgOIxKcwAr9qzO3IBWXM8zrf10rs8GhmGKEsufV7lZk7I3teJlGawDFeW628NgfWwBvA0t+rPbtcvj31d2YuxyEPviCnu4vq2ZIO0Z2F3Bk3NNcXV8xtEefmSlM402jbxJUq7p5CaY6D4dHghXcGtsUWTUSWmRcBhiYXahdCaRZN0XCpS0ukdkJOKTdNrQ7GEKvQ+gA8bmdRe+8OJFauWzU5nljG98ZdXRoPkN/zjGyo+6i4Gi7bZfA7Wy1bsbKSJ5EhNlNA87UITbISjBFa8zzFSJm9UoJsptoBZngdaiANURZv6vUuNiyEUt9eXBWDhGW95IiyZnocfPqACyLgdHeX8sgCAheX+GuZjz0/QH1eHAzo/jbfL8QhggUpEAtGd69o3QsXm21Ntm++ekWiJ4JXQ1p/MSXidjzfjAJNeSNfywRjaIQTaSuaCj16Uf9sRiwYU+szWwM6hlCd3Cdv+1Zj96UEvzcfxQgABK4MymzDvpYFYjkToehJuKQA5fbn4oC5Bdd1AyoVLtbA7MDLzWKu6nByKQBD8MKsx469yPOMj2BryPIaK+LJORGacDZgiPZZOvxiz53L2MW1OzFWN/r1YRBiTU/qUS4J2hVg=
  email: lotosbin@gmail.com
  provider: npm
